# Generated by Django 5.0.6 on 2024-07-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trends", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_id", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("design_link", models.URLField()),
            ],
        ),
    ]
