# Generated by Django 5.0.7 on 2024-07-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
