# Generated by Django 5.0.7 on 2024-07-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsubmission',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='user_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
