# Generated by Django 5.0.7 on 2024-07-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0005_designsubmission_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='designsubmission',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='designsubmission',
            name='user_password',
        ),
    ]
