# Generated by Django 5.0.7 on 2024-07-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0006_signup_remove_designsubmission_user_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
